# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "NTU Hall 3"
license = "MIT"
description = "The theme used for Hall 3's official website."
homepage = "http://hall3.netlify.com"
tags = ["college", "university", "singapore", "hall 3", "hall"]
features = []
min_version = "0.1.0"

[author]
  name = "Zildjian Garcia"
  homepage = "https://www.linkedin.com/in/zildjian-aquino-garcia/"
